local addon_name, addon_data = ...
addon_data.localization_table = {}
local L = addon_data.localization_table

-- Translation of DE, ES, MX, FR, IT, BR, KOR, added RU and added CN, TW were done using AI. If any major errors please report with the correct translation

	--Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Thank you for installing WeaponSwingTimer Version"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "by WatchYourSixx! Use |cFFFFC300/wst|r for more options."
	L["Unexpected Unit Type in MissHandler()."]="Unexpected Unit Type in MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."]="Unexpected Unit Type in SpellHandler()."

	--Config
	L["Global Bar Settings"]="Global Bar Settings"
	L["Melee Settings"]="Melee Settings"
	L["Hunter & Wand Settings"]="Hunter & Wand Settings"
	L[" Lock All Bars"]=" Lock All Bars"
	L["Locks all of the swing bar frames, preventing them from being dragged."]="Locks all of the swing bar frames, preventing them from being dragged."
	L[" Welcome Message"]=" Welcome Message"
	L["Displays the welcome message upon login/reload. Uncheck to disable."]="Displays the welcome message upon login/reload. Uncheck to disable."
	L["Ranged Settings"]="Ranged Settings"
	L["Profiles"]="Profiles"
	L["Profiles let you save multiple layouts and quickly switch between them."]="Profiles let you save multiple layouts and quickly switch between them."
	L["New profile name"]="New profile name"
	L["Create"]="Create"
	L["Copy from..."]="Copy from..."
	L["Reset Active Profile"]="Reset Active Profile"
	L["Delete Active Profile"]="Delete Active Profile"
	L["Delete active profile? This cannot be undone."]="Delete active profile? This cannot be undone."
	L["Reset profile to defaults?"]="Reset profile to defaults?"

	--Player
	L["Player Swing Bar Settings"]="Player Swing Bar Settings"
    L["Enables the player's swing bars."]="Enables the player's swing bars."
    L["Enables the player's off-hand swing bar."]="Enables the player's off-hand swing bar."
    L["Enables the player bar's border."]="Enables the player bar's border."
    L["Enables the classic texture for the player's bars."]="Enables the classic texture for the player's bars."
    L["Enables the player's left side text."]="Enables the player's left side text."
    L["Enables the player's right side text."]="Enables the player's right side text."
	L["Show Paladin Twist"]=" Show Paladin Twist"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."]="Show 0.4s marker before swing to help with seal twisting. Apply seal after this."
	L["Show Paladin GCD"]=" Show Paladin GCD"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."]="Show GCD marker before swing to help with seal twisting. Apply first seal before this."
	L["Paladin Marker offset"]="Paladin Marker offset"
	--Target
	L["Target Swing Bar Settings"]="Target Swing Bar Settings"
	L["Enables the target's swing bars."]="Enables the target's swing bars."
    L["Enables the target's off-hand swing bar."]="Enables the target's off-hand swing bar."
    L["Enables the target bar's border."]="Enables the target bar's border."
    L["Enables the classic texture for the target's bars."]="Enables the classic texture for the target's bars."
    L["Enables the target's left side text."]="Enables the target's left side text."
    L["Enables the target's right side text."]="Enables the target's right side text."
	--Shot
	L["Failed"] = "Failed"
	L["Interrupted"] = "Interrupted"
	L["Hunter & Wand Shot Bar Settings"]="Hunter & Wand Shot Bar Settings"
	L["General Settings"]="General Settings"
	L["YaHT / One bar"]=" YaHT / One bar"
    L["Changes the Auto Shot bar to a single bar that fills from left to right"]="Changes the Auto Shot bar to a single bar that fills from left to right"
    L["Show Text"]=" Show Text"
	L["Show Cast Text"]=" Show Cast Text"
    L["Enables the shot bar text."]="Enables the shot bar text."
	L["Enables the cast bar text."]="Enables the cast bar text."
    L["Auto Shot Cooldown Color"]="Auto Shot Cooldown Color"
    L["Auto Shot Cast Color"]="Auto Shot Cast Color"
	L["Hunter Specific Settings"]="Hunter Specific Settings"
    L["Aimed Shot cast bar"]=" Aimed Shot cast bar"
    L["Allows the cast bar to show Aimed Shot casts."]="Allows the cast bar to show Aimed Shot casts."
    L["Multi-Shot cast bar"]=" Multi-Shot cast bar"
    L["Allows the cast bar to show Multi-Shot casts."]="Allows the cast bar to show Multi-Shot casts."
    L["Latency bar"]=" Latency bar"
    L["Shows a bar that represents latency on cast bar."]="Shows a bar that represents latency on cast bar."
    L["Multi-Shot clip bar"]=" Multi-Shot clip bar"
    L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."]="Shows a bar that represents when a Multi-Shot would clip an Auto Shot."
	L["Auto Shot delay timer"] = " Auto Shot delay timer"
	L["Shows a timer that represents when Auto shot is delayed."] = "Shows a timer that represents when Auto shot is delayed."
    L["Multi-Shot Clip Color"]="Multi-Shot Clip Color"
	L["Spell Bar Unlocked"] = "Spell Bar Unlocked"
	L["Player Spell Bar Settings"] = "Player Spell Bar Settings"

    --Common
	L["Main-Hand"]="Main-Hand"
	L["Off-Hand"]="Off-Hand"
	L["Enable"]=" Enable"
    L["Show Off-Hand"]=" Show Off-Hand"
    L["Show border"]=" Show border"
    L["Classic bars"]=" Classic bars"
    L["Fill / Empty"]=" Fill / Empty"
    L["Determines if the bar is full or empty when a swing is ready."]="Determines if the bar is full or empty when a swing is ready."
    L["Show Left Text"]=" Show Left Text"
    L["Show Right Text"]=" Show Right Text"
	L["Bar Width"]="Bar Width"
    L["Bar Height"]="Bar Height"
    L["X Offset"]="X Offset"
    L["Y Offset"]="Y Offset"
	L["Main-hand Bar Color"]="Main-hand Bar Color"
    L["Main-hand Bar Text Color"]="Main-hand Bar Text Color"
    L["Off-hand Bar Color"]="Off-hand Bar Color"
    L["Off-hand Bar Text Color"]="Off-hand Bar Text Color"
	L["In Combat Alpha"]="In Combat Alpha"
    L["Out of Combat Alpha"]="Out of Combat Alpha"
    L["Backplane Alpha"]="Backplane Alpha"
	L["Bar Explanation"]="Bar Explanation"
	L["Font Size"] ="Font Size"

	--Spell
	L["Auto Shot"]="Auto Shot"
	L["Feign Death"] = "Feign Death"
	L["Trueshot Aura"] = "Trueshot Aura"
	L["Multi-Shot"]="Multi-Shot"
	L["Aimed Shot"]="Aimed Shot"
	L["Shoot"]="Shoot"
	L["Quick Shots"]="Quick Shots"
	L["Rapid Shot"]="Rapid Shot"
	L["Berserking"]="Berserking"
	L["Kiss of the Spider"]="Kiss of the Spider"
	L["Curse of Tongues"]="Curse of Tongues"

if GetLocale() == "deDE" then

	-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Danke, dass du WeaponSwingTimer installiert hast"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "von WatchYourSixx! Nutze |cFFFFC300/wst|r für weitere Optionen."
	L["Unexpected Unit Type in MissHandler()."] = "Unerwarteter Einheitentyp in MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."] = "Unerwarteter Einheitentyp in SpellHandler()."

	-- Config
	L["Global Bar Settings"] = "Globale Balkeneinstellungen"
	L["Melee Settings"] = "Nahkampfeinstellungen"
	L["Hunter & Wand Settings"] = "Jäger- & Zauberstab-Einstellungen"
	L[" Lock All Bars"] = " Alle Balken sperren"
	L["Locks all of the swing bar frames, preventing them from being dragged."] ="Sperrt alle Schwungbalken und verhindert, dass sie verschoben werden."
	L[" Welcome Message"] = " Willkommensnachricht"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] ="Zeigt die Willkommensnachricht beim Login oder Neuladen an. Deaktivieren zum Ausschalten."
	L["Ranged Settings"] = "Fernkampfeinstellungen"

	L["Profiles"] = "Profile"
	L["Profiles let you save multiple layouts and quickly switch between them."] ="Profile ermöglichen es, mehrere Layouts zu speichern und schnell zwischen ihnen zu wechseln."
	L["New profile name"] = "Neuer Profilname"
	L["Create"] = "Erstellen"
	L["Copy from..."] = "Kopieren von..."
	L["Reset Active Profile"] = "Aktives Profil zurücksetzen"
	L["Delete Active Profile"] = "Aktives Profil löschen"
	L["Delete active profile? This cannot be undone."] ="Aktives Profil löschen? Dies kann nicht rückgängig gemacht werden."
	L["Reset profile to defaults?"] = "Profil auf Standardeinstellungen zurücksetzen?"

	-- Player
	L["Player Swing Bar Settings"] = "Schwungbalken – Spieler"
	L["Enables the player's swing bars."] = "Aktiviert die Schwungbalken des Spielers."
	L["Enables the player's off-hand swing bar."] = "Aktiviert den Nebenhand-Schwungbalken des Spielers."
	L["Enables the player bar's border."] = "Aktiviert den Rahmen des Spielerbalkens."
	L["Enables the classic texture for the player's bars."] ="Aktiviert die klassische Textur für die Spielerbalken."
	L["Enables the player's left side text."] ="Aktiviert den Text auf der linken Seite des Spielerbalkens."
	L["Enables the player's right side text."] ="Aktiviert den Text auf der rechten Seite des Spielerbalkens."

	L["Show Paladin Twist"] = "Paladin-Twist anzeigen"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] ="Zeigt eine 0,4-Sekunden-Markierung vor dem Schlag an, um Seal-Twisting zu erleichtern. Siegel danach anwenden."
	L["Show Paladin GCD"] = "Paladin-GCD anzeigen"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] ="Zeigt eine GCD-Markierung vor dem Schlag an, um Seal-Twisting zu erleichtern. Erstes Siegel davor anwenden."
	L["Paladin Marker offset"] = "Versatz der Paladin-Markierung"

	-- Target
	L["Target Swing Bar Settings"] = "Schwungbalken – Ziel"
	L["Enables the target's swing bars."] = "Aktiviert die Schwungbalken des Ziels."
	L["Enables the target's off-hand swing bar."] = "Aktiviert den Nebenhand-Schwungbalken des Ziels."
	L["Enables the target bar's border."] = "Aktiviert den Rahmen des Zielbalkens."
	L["Enables the classic texture for the target's bars."] ="Aktiviert die klassische Textur für die Zielbalken."
	L["Enables the target's left side text."] ="Aktiviert den Text auf der linken Seite des Zielbalkens."
	L["Enables the target's right side text."] ="Aktiviert den Text auf der rechten Seite des Zielbalkens."

	-- Shot
	L["Failed"] = "Fehlgeschlagen"
	L["Interrupted"] = "Unterbrochen"
	L["Hunter & Wand Shot Bar Settings"] = "Schussbalken – Jäger & Zauberstab"
	L["General Settings"] = "Allgemeine Einstellungen"
	L["YaHT / One bar"] = "YaHT / Ein Balken"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] ="Ändert den Auto-Schuss-Balken zu einem einzelnen Balken, der sich von links nach rechts füllt."
	L["Show Text"] = " Text anzeigen"
	L["Show Cast Text"] = " Zaubertext anzeigen"
	L["Enables the shot bar text."] = "Aktiviert den Text im Schussbalken."
	L["Enables the cast bar text."] = "Aktiviert den Text im Zauberbalken."
	L["Auto Shot Cooldown Color"] = "Farbe: Auto-Schuss-Abklingzeit"
	L["Auto Shot Cast Color"] = "Farbe: Auto-Schuss-Zauberzeit"

	L["Hunter Specific Settings"] = "Jägerspezifische Einstellungen"
	L["Aimed Shot cast bar"] = "Gezielter-Schuss-Zauberbalken"
	L["Allows the cast bar to show Aimed Shot casts."] ="Erlaubt dem Zauberbalken, Gezielter Schuss anzuzeigen."
	L["Multi-Shot cast bar"] = "Mehrfachschuss-Zauberbalken"
	L["Allows the cast bar to show Multi-Shot casts."] ="Erlaubt dem Zauberbalken, Mehrfachschuss anzuzeigen."
	L["Latency bar"] = "Latenzbalken"
	L["Shows a bar that represents latency on cast bar."] ="Zeigt einen Balken an, der die Latenz im Zauberbalken darstellt."
	L["Multi-Shot clip bar"] = "Mehrfachschuss-Clip-Balken"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] ="Zeigt an, wann ein Mehrfachschuss einen Auto-Schuss unterbrechen würde."
	L["Auto Shot delay timer"] = "Auto-Schuss-Verzögerungstimer"
	L["Shows a timer that represents when Auto shot is delayed."] ="Zeigt einen Timer an, wenn sich der Auto-Schuss verzögert."
	L["Multi-Shot Clip Color"] = "Farbe: Mehrfachschuss-Clip"

	L["Spell Bar Unlocked"] = "Zauberbalken entsperrt"
	L["Player Spell Bar Settings"] = "Zauberbalken – Spieler"

	-- Common
	L["Main-Hand"] = "Haupthand"
	L["Off-Hand"] = "Nebenhand"
	L["Enable"] = " Aktivieren"
	L["Show Off-Hand"] = " Nebenhand anzeigen"
	L["Show border"] = " Rahmen anzeigen"
	L["Classic bars"] = " Klassische Balken"
	L["Fill / Empty"] = " Füllen / Leeren"
	L["Determines if the bar is full or empty when a swing is ready."] ="Legt fest, ob der Balken voll oder leer ist, wenn ein Schlag bereit ist."
	L["Show Left Text"] = " Linken Text anzeigen"
	L["Show Right Text"] = " Rechten Text anzeigen"
	L["Bar Width"] = "Balkenbreite"
	L["Bar Height"] = "Balkenhöhe"
	L["X Offset"] = "X-Versatz"
	L["Y Offset"] = "Y-Versatz"
	L["Main-hand Bar Color"] = "Farbe: Haupthand-Balken"
	L["Main-hand Bar Text Color"] = "Farbe: Haupthand-Text"
	L["Off-hand Bar Color"] = "Farbe: Nebenhand-Balken"
	L["Off-hand Bar Text Color"] = "Farbe: Nebenhand-Text"
	L["In Combat Alpha"] = "Transparenz im Kampf"
	L["Out of Combat Alpha"] = "Transparenz außerhalb des Kampfes"
	L["Backplane Alpha"] = "Hintergrundtransparenz"
	L["Bar Explanation"] = "Balkenerklärung"
	L["Font Size"] = "Schriftgröße"

	-- Spell, leaving commented out since these must match exactly
	-- L["Auto Shot"] = "Automatischer Schuss"
	-- L["Feign Death"] = "Totstellen"
	-- L["Trueshot Aura"] = "Aura des Volltreffers"
	-- L["Multi-Shot"] = "Mehrfachschuss"
	-- L["Aimed Shot"] = "Gezielter Schuss"
	-- L["Shoot"] = "Schießen"
	-- L["Quick Shots"] = "Schnelle Schüsse"
	-- L["Rapid Shot"] = "Schnellfeuer"
	-- L["Berserking"] = "Berserker"
	-- L["Kiss of the Spider"] = "Kuss der Spinne"
	-- L["Curse of Tongues"] = "Fluch der Sprachen"

end

if GetLocale() == "esES" or GetLocale() == "esMX" then

	-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Gracias por instalar WeaponSwingTimer"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] ="por WatchYourSixx. Usa |cFFFFC300/wst|r para más opciones."
	L["Unexpected Unit Type in MissHandler()."] ="Tipo de unidad inesperado en MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."] ="Tipo de unidad inesperado en SpellHandler()."

	-- Config
	L["Global Bar Settings"] = "Configuración global de barras"
	L["Melee Settings"] = "Configuración de combate cuerpo a cuerpo"
	L["Hunter & Wand Settings"] = "Configuración de cazador y varitas"
	L[" Lock All Bars"] = " Bloquear todas las barras"
	L["Locks all of the swing bar frames, preventing them from being dragged."] ="Bloquea todas las barras de golpe, evitando que se puedan mover."
	L[" Welcome Message"] = " Mensaje de bienvenida"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] ="Muestra el mensaje de bienvenida al iniciar sesión o recargar. Desmárcalo para desactivar."
	L["Ranged Settings"] = "Configuración a distancia"

	L["Profiles"] = "Perfiles"
	L["Profiles let you save multiple layouts and quickly switch between them."] ="Los perfiles te permiten guardar varios diseños y cambiar rápidamente entre ellos."
	L["New profile name"] = "Nombre del nuevo perfil"
	L["Create"] = "Crear"
	L["Copy from..."] = "Copiar de..."
	L["Reset Active Profile"] = "Restablecer perfil activo"
	L["Delete Active Profile"] = "Eliminar perfil activo"
	L["Delete active profile? This cannot be undone."] ="¿Eliminar el perfil activo? Esta acción no se puede deshacer."
	L["Reset profile to defaults?"] ="¿Restablecer el perfil a los valores predeterminados?"

	-- Player
	L["Player Swing Bar Settings"] = "Configuración de barras de golpe del jugador"
	L["Enables the player's swing bars."] ="Habilita las barras de golpe del jugador."
	L["Enables the player's off-hand swing bar."] ="Habilita la barra de golpe de la mano secundaria del jugador."
	L["Enables the player bar's border."] ="Habilita el borde de la barra del jugador."
	L["Enables the classic texture for the player's bars."] ="Habilita la textura clásica para las barras del jugador."
	L["Enables the player's left side text."] ="Habilita el texto del lado izquierdo de la barra del jugador."
	L["Enables the player's right side text."] ="Habilita el texto del lado derecho de la barra del jugador."

	L["Show Paladin Twist"] = "Mostrar twist del paladín"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] ="Muestra un marcador 0,4 s antes del golpe para ayudar con el twist de sellos. Aplica el sello después de este marcador."
	L["Show Paladin GCD"] = "Mostrar GCD del paladín"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] ="Muestra un marcador de GCD antes del golpe para ayudar con el twist de sellos. Aplica el primer sello antes de este marcador."
	L["Paladin Marker offset"] = "Desplazamiento del marcador del paladín"

	-- Target
	L["Target Swing Bar Settings"] = "Configuración de barras de golpe del objetivo"
	L["Enables the target's swing bars."] ="Habilita las barras de golpe del objetivo."
	L["Enables the target's off-hand swing bar."] ="Habilita la barra de golpe de la mano secundaria del objetivo."
	L["Enables the target bar's border."] ="Habilita el borde de la barra del objetivo."
	L["Enables the classic texture for the target's bars."] ="Habilita la textura clásica para las barras del objetivo."
	L["Enables the target's left side text."] ="Habilita el texto del lado izquierdo de la barra del objetivo."
	L["Enables the target's right side text."] ="Habilita el texto del lado derecho de la barra del objetivo."

	-- Shot
	L["Failed"] = "Fallido"
	L["Interrupted"] = "Interrumpido"
	L["Hunter & Wand Shot Bar Settings"] ="Configuración de barras de disparo de cazador y varitas"
	L["General Settings"] = "Configuración general"
	L["YaHT / One bar"] = "YaHT / Una barra"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] ="Cambia la barra de Disparo automático a una sola barra que se llena de izquierda a derecha."
	L["Show Text"] = " Mostrar texto"
	L["Show Cast Text"] = " Mostrar texto de lanzamiento"
	L["Enables the shot bar text."] ="Habilita el texto en la barra de disparo."
	L["Enables the cast bar text."] ="Habilita el texto en la barra de lanzamiento."
	L["Auto Shot Cooldown Color"] ="Color del tiempo de reutilización del Disparo automático"
	L["Auto Shot Cast Color"] ="Color del lanzamiento del Disparo automático"

	L["Hunter Specific Settings"] ="Configuración específica del cazador"
	L["Aimed Shot cast bar"] ="Barra de lanzamiento de Disparo apuntado"
	L["Allows the cast bar to show Aimed Shot casts."] ="Permite que la barra de lanzamiento muestre Disparo apuntado."
	L["Multi-Shot cast bar"] ="Barra de lanzamiento de Multidisparo"
	L["Allows the cast bar to show Multi-Shot casts."] ="Permite que la barra de lanzamiento muestre Multidisparo."
	L["Latency bar"] = "Barra de latencia"
	L["Shows a bar that represents latency on cast bar."] ="Muestra una barra que representa la latencia en la barra de lanzamiento."
	L["Multi-Shot clip bar"] ="Barra de recorte de Multidisparo"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] ="Muestra cuándo un Multidisparo interrumpiría un Disparo automático."
	L["Auto Shot delay timer"] ="Temporizador de retraso del Disparo automático"
	L["Shows a timer that represents when Auto shot is delayed."] ="Muestra un temporizador cuando el Disparo automático se retrasa."
	L["Multi-Shot Clip Color"] ="Color del recorte de Multidisparo"

	L["Spell Bar Unlocked"] = "Barra de hechizos desbloqueada"
	L["Player Spell Bar Settings"] ="Configuración de la barra de hechizos del jugador"

	-- Common
	L["Main-Hand"] = "Mano principal"
	L["Off-Hand"] = "Mano secundaria"
	L["Enable"] = " Activar"
	L["Show Off-Hand"] = " Mostrar mano secundaria"
	L["Show border"] = " Mostrar borde"
	L["Classic bars"] = " Barras clásicas"
	L["Fill / Empty"] = " Llenar / Vaciar"
	L["Determines if the bar is full or empty when a swing is ready."] ="Determina si la barra está llena o vacía cuando el golpe está listo."
	L["Show Left Text"] = " Mostrar texto izquierdo"
	L["Show Right Text"] = " Mostrar texto derecho"
	L["Bar Width"] = "Ancho de la barra"
	L["Bar Height"] = "Altura de la barra"
	L["X Offset"] = "Desplazamiento X"
	L["Y Offset"] = "Desplazamiento Y"
	L["Main-hand Bar Color"] ="Color de la barra de la mano principal"
	L["Main-hand Bar Text Color"] ="Color del texto de la mano principal"
	L["Off-hand Bar Color"] ="Color de la barra de la mano secundaria"
	L["Off-hand Bar Text Color"] ="Color del texto de la mano secundaria"
	L["In Combat Alpha"] ="Transparencia en combate"
	L["Out of Combat Alpha"] ="Transparencia fuera de combate"
	L["Backplane Alpha"] ="Transparencia del fondo"
	L["Bar Explanation"] ="Explicación de las barras"
	L["Font Size"] = "Tamaño de fuente"

end

if GetLocale() == "frFR" then
	-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Merci d'avoir installé WeaponSwingTimer"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "par WatchYourSixx. Utilisez |cFFFFC300/wst|r pour plus d’options."
	L["Unexpected Unit Type in MissHandler()."] = "Type d’unité inattendu dans MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."] = "Type d’unité inattendu dans SpellHandler()."

	-- Config
	L["Global Bar Settings"] = "Paramètres globaux des barres"
	L["Melee Settings"] = "Paramètres de mêlée"
	L["Hunter & Wand Settings"] = "Paramètres du chasseur et des baguettes"
	L[" Lock All Bars"] = " Verrouiller toutes les barres"
	L["Locks all of the swing bar frames, preventing them from being dragged."] = "Verrouille toutes les barres de frappe et empêche leur déplacement."
	L[" Welcome Message"] = " Message de bienvenue"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "Affiche le message de bienvenue à la connexion ou au rechargement. Décochez pour désactiver."
	L["Ranged Settings"] = "Paramètres à distance"
	L["Profiles"] = "Profils"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "Les profils permettent d’enregistrer plusieurs dispositions et de passer rapidement de l’une à l’autre."
	L["New profile name"] = "Nom du nouveau profil"
	L["Create"] = "Créer"
	L["Copy from..."] = "Copier depuis..."
	L["Reset Active Profile"] = "Réinitialiser le profil actif"
	L["Delete Active Profile"] = "Supprimer le profil actif"
	L["Delete active profile? This cannot be undone."] = "Supprimer le profil actif ? Cette action est irréversible."
	L["Reset profile to defaults?"] = "Réinitialiser le profil aux paramètres par défaut ?"

	-- Player
	L["Player Swing Bar Settings"] = "Paramètres des barres de frappe du joueur"
	L["Enables the player's swing bars."] = "Active les barres de frappe du joueur."
	L["Enables the player's off-hand swing bar."] = "Active la barre de frappe de la main secondaire du joueur."
	L["Enables the player bar's border."] = "Active le contour de la barre du joueur."
	L["Enables the classic texture for the player's bars."] = "Active la texture classique pour les barres du joueur."
	L["Enables the player's left side text."] = "Active le texte sur le côté gauche de la barre du joueur."
	L["Enables the player's right side text."] = "Active le texte sur le côté droit de la barre du joueur."
	L["Show Paladin Twist"] = "Afficher le twist du paladin"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "Affiche un marqueur 0,4 s avant la frappe pour aider au twist des sceaux. Appliquez le sceau après ce marqueur."
	L["Show Paladin GCD"] = "Afficher le GCD du paladin"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "Affiche un marqueur de GCD avant la frappe pour aider au twist des sceaux. Appliquez le premier sceau avant ce marqueur."
	L["Paladin Marker offset"] = "Décalage du marqueur du paladin"

	-- Target
	L["Target Swing Bar Settings"] = "Paramètres des barres de frappe de la cible"
	L["Enables the target's swing bars."] = "Active les barres de frappe de la cible."
	L["Enables the target's off-hand swing bar."] = "Active la barre de frappe de la main secondaire de la cible."
	L["Enables the target bar's border."] = "Active le contour de la barre de la cible."
	L["Enables the classic texture for the target's bars."] = "Active la texture classique pour les barres de la cible."
	L["Enables the target's left side text."] = "Active le texte sur le côté gauche de la barre de la cible."
	L["Enables the target's right side text."] = "Active le texte sur le côté droit de la barre de la cible."

	-- Shot
	L["Failed"] = "Échec"
	L["Interrupted"] = "Interrompu"
	L["Hunter & Wand Shot Bar Settings"] = "Paramètres des barres de tir du chasseur et des baguettes"
	L["General Settings"] = "Paramètres généraux"
	L["YaHT / One bar"] = "YaHT / Une barre"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] = "Transforme la barre de Tir automatique en une seule barre qui se remplit de gauche à droite."
	L["Show Text"] = " Afficher le texte"
	L["Show Cast Text"] = " Afficher le texte d’incantation"
	L["Enables the shot bar text."] = "Active le texte sur la barre de tir."
	L["Enables the cast bar text."] = "Active le texte sur la barre d’incantation."
	L["Auto Shot Cooldown Color"] = "Couleur du temps de recharge du Tir automatique"
	L["Auto Shot Cast Color"] = "Couleur de l’incantation du Tir automatique"
	L["Hunter Specific Settings"] = "Paramètres spécifiques du chasseur"
	L["Aimed Shot cast bar"] = "Barre d’incantation de Tir des arcanes"
	L["Allows the cast bar to show Aimed Shot casts."] = "Permet d’afficher Tir des arcanes sur la barre d’incantation."
	L["Multi-Shot cast bar"] = "Barre d’incantation de Flèches multiples"
	L["Allows the cast bar to show Multi-Shot casts."] = "Permet d’afficher Flèches multiples sur la barre d’incantation."
	L["Latency bar"] = "Barre de latence"
	L["Shows a bar that represents latency on cast bar."] = "Affiche une barre représentant la latence sur la barre d’incantation."
	L["Multi-Shot clip bar"] = "Barre de chevauchement de Flèches multiples"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] = "Indique quand Flèches multiples interrompt un Tir automatique."
	L["Auto Shot delay timer"] = "Minuteur de délai du Tir automatique"
	L["Shows a timer that represents when Auto shot is delayed."] = "Affiche un minuteur lorsque le Tir automatique est retardé."
	L["Multi-Shot Clip Color"] = "Couleur du chevauchement de Flèches multiples"
	L["Spell Bar Unlocked"] = "Barre de sorts déverrouillée"
	L["Player Spell Bar Settings"] = "Paramètres de la barre de sorts du joueur"

	-- Common
	L["Main-Hand"] = "Main principale"
	L["Off-Hand"] = "Main secondaire"
	L["Enable"] = " Activer"
	L["Show Off-Hand"] = " Afficher la main secondaire"
	L["Show border"] = " Afficher le contour"
	L["Classic bars"] = " Barres classiques"
	L["Fill / Empty"] = " Remplir / Vider"
	L["Determines if the bar is full or empty when a swing is ready."] = "Détermine si la barre est pleine ou vide lorsque la frappe est prête."
	L["Show Left Text"] = " Afficher le texte gauche"
	L["Show Right Text"] = " Afficher le texte droit"
	L["Bar Width"] = "Largeur de la barre"
	L["Bar Height"] = "Hauteur de la barre"
	L["X Offset"] = "Décalage X"
	L["Y Offset"] = "Décalage Y"
	L["Main-hand Bar Color"] = "Couleur de la barre de la main principale"
	L["Main-hand Bar Text Color"] = "Couleur du texte de la main principale"
	L["Off-hand Bar Color"] = "Couleur de la barre de la main secondaire"
	L["Off-hand Bar Text Color"] = "Couleur du texte de la main secondaire"
	L["In Combat Alpha"] = "Transparence en combat"
	L["Out of Combat Alpha"] = "Transparence hors combat"
	L["Backplane Alpha"] = "Transparence de l’arrière-plan"
	L["Bar Explanation"] = "Explication des barres"
	L["Font Size"] = "Taille de la police"
end

if GetLocale() == "itIT" then
	-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Grazie per aver installato WeaponSwingTimer"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "di WatchYourSixx. Usa |cFFFFC300/wst|r per più opzioni."
	L["Unexpected Unit Type in MissHandler()."] = "Tipo di unità inatteso in MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."] = "Tipo di unità inatteso in SpellHandler()."

	-- Config
	L["Global Bar Settings"] = "Impostazioni globali delle barre"
	L["Melee Settings"] = "Impostazioni di combattimento corpo a corpo"
	L["Hunter & Wand Settings"] = "Impostazioni di cacciatore e bacchette"
	L[" Lock All Bars"] = " Blocca tutte le barre"
	L["Locks all of the swing bar frames, preventing them from being dragged."] = "Blocca tutte le barre di attacco impedendo che vengano spostate."
	L[" Welcome Message"] = " Messaggio di benvenuto"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "Mostra il messaggio di benvenuto all’accesso o al ricaricamento. Deseleziona per disattivare."
	L["Ranged Settings"] = "Impostazioni a distanza"
	L["Profiles"] = "Profili"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "I profili consentono di salvare più layout e passare rapidamente da uno all’altro."
	L["New profile name"] = "Nome del nuovo profilo"
	L["Create"] = "Crea"
	L["Copy from..."] = "Copia da..."
	L["Reset Active Profile"] = "Reimposta profilo attivo"
	L["Delete Active Profile"] = "Elimina profilo attivo"
	L["Delete active profile? This cannot be undone."] = "Eliminare il profilo attivo? Questa azione non può essere annullata."
	L["Reset profile to defaults?"] = "Reimpostare il profilo ai valori predefiniti?"

	-- Player
	L["Player Swing Bar Settings"] = "Impostazioni barre di attacco del giocatore"
	L["Enables the player's swing bars."] = "Abilita le barre di attacco del giocatore."
	L["Enables the player's off-hand swing bar."] = "Abilita la barra di attacco della mano secondaria del giocatore."
	L["Enables the player bar's border."] = "Abilita il bordo della barra del giocatore."
	L["Enables the classic texture for the player's bars."] = "Abilita la texture classica per le barre del giocatore."
	L["Enables the player's left side text."] = "Abilita il testo sul lato sinistro della barra del giocatore."
	L["Enables the player's right side text."] = "Abilita il testo sul lato destro della barra del giocatore."
	L["Show Paladin Twist"] = "Mostra twist del paladino"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "Mostra un indicatore di 0,4 s prima dell’attacco per aiutare con il twist dei sigilli. Applica il sigillo dopo questo indicatore."
	L["Show Paladin GCD"] = "Mostra GCD del paladino"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "Mostra un indicatore di GCD prima dell’attacco per aiutare con il twist dei sigilli. Applica il primo sigillo prima di questo indicatore."
	L["Paladin Marker offset"] = "Offset indicatore del paladino"

	-- Target
	L["Target Swing Bar Settings"] = "Impostazioni barre di attacco del bersaglio"
	L["Enables the target's swing bars."] = "Abilita le barre di attacco del bersaglio."
	L["Enables the target's off-hand swing bar."] = "Abilita la barra di attacco della mano secondaria del bersaglio."
	L["Enables the target bar's border."] = "Abilita il bordo della barra del bersaglio."
	L["Enables the classic texture for the target's bars."] = "Abilita la texture classica per le barre del bersaglio."
	L["Enables the target's left side text."] = "Abilita il testo sul lato sinistro della barra del bersaglio."
	L["Enables the target's right side text."] = "Abilita il testo sul lato destro della barra del bersaglio."

	-- Shot
	L["Failed"] = "Fallito"
	L["Interrupted"] = "Interrotto"
	L["Hunter & Wand Shot Bar Settings"] = "Impostazioni barre di tiro di cacciatore e bacchette"
	L["General Settings"] = "Impostazioni generali"
	L["YaHT / One bar"] = "YaHT / Barra singola"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] = "Trasforma la barra di Tiro automatico in una singola barra che si riempie da sinistra a destra."
	L["Show Text"] = " Mostra testo"
	L["Show Cast Text"] = " Mostra testo di lancio"
	L["Enables the shot bar text."] = "Abilita il testo sulla barra di tiro."
	L["Enables the cast bar text."] = "Abilita il testo sulla barra di lancio."
	L["Auto Shot Cooldown Color"] = "Colore recupero Tiro automatico"
	L["Auto Shot Cast Color"] = "Colore lancio Tiro automatico"
	L["Hunter Specific Settings"] = "Impostazioni specifiche del cacciatore"
	L["Aimed Shot cast bar"] = "Barra di lancio di Tiro mirato"
	L["Allows the cast bar to show Aimed Shot casts."] = "Consente alla barra di lancio di mostrare Tiro mirato."
	L["Multi-Shot cast bar"] = "Barra di lancio di Tiro multiplo"
	L["Allows the cast bar to show Multi-Shot casts."] = "Consente alla barra di lancio di mostrare Tiro multiplo."
	L["Latency bar"] = "Barra di latenza"
	L["Shows a bar that represents latency on cast bar."] = "Mostra una barra che rappresenta la latenza sulla barra di lancio."
	L["Multi-Shot clip bar"] = "Barra di sovrapposizione di Tiro multiplo"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] = "Mostra quando Tiro multiplo interromperebbe un Tiro automatico."
	L["Auto Shot delay timer"] = "Timer di ritardo del Tiro automatico"
	L["Shows a timer that represents when Auto shot is delayed."] = "Mostra un timer quando il Tiro automatico è in ritardo."
	L["Multi-Shot Clip Color"] = "Colore sovrapposizione Tiro multiplo"
	L["Spell Bar Unlocked"] = "Barra incantesimi sbloccata"
	L["Player Spell Bar Settings"] = "Impostazioni barra incantesimi del giocatore"

	-- Common
	L["Main-Hand"] = "Mano principale"
	L["Off-Hand"] = "Mano secondaria"
	L["Enable"] = " Abilita"
	L["Show Off-Hand"] = " Mostra mano secondaria"
	L["Show border"] = " Mostra bordo"
	L["Classic bars"] = " Barre classiche"
	L["Fill / Empty"] = " Riempi / Svuota"
	L["Determines if the bar is full or empty when a swing is ready."] = "Determina se la barra è piena o vuota quando l’attacco è pronto."
	L["Show Left Text"] = " Mostra testo sinistro"
	L["Show Right Text"] = " Mostra testo destro"
	L["Bar Width"] = "Larghezza barra"
	L["Bar Height"] = "Altezza barra"
	L["X Offset"] = "Offset X"
	L["Y Offset"] = "Offset Y"
	L["Main-hand Bar Color"] = "Colore barra mano principale"
	L["Main-hand Bar Text Color"] = "Colore testo mano principale"
	L["Off-hand Bar Color"] = "Colore barra mano secondaria"
	L["Off-hand Bar Text Color"] = "Colore testo mano secondaria"
	L["In Combat Alpha"] = "Trasparenza in combattimento"
	L["Out of Combat Alpha"] = "Trasparenza fuori combattimento"
	L["Backplane Alpha"] = "Trasparenza dello sfondo"
	L["Bar Explanation"] = "Spiegazione delle barre"
	L["Font Size"] = "Dimensione carattere"
end

if GetLocale() == "koKR" then
	-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "WeaponSwingTimer를 설치해 주셔서 감사합니다"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "제작: WatchYourSixx. 더 많은 옵션은 |cFFFFC300/wst|r을 사용하세요."
	L["Unexpected Unit Type in MissHandler()."] = "MissHandler()에서 예상치 못한 유닛 유형이 감지되었습니다."
	L["Unexpected Unit Type in SpellHandler()."] = "SpellHandler()에서 예상치 못한 유닛 유형이 감지되었습니다."

	-- Config
	L["Global Bar Settings"] = "전역 바 설정"
	L["Melee Settings"] = "근접 전투 설정"
	L["Hunter & Wand Settings"] = "사냥꾼 및 마법봉 설정"
	L[" Lock All Bars"] = " 모든 바 잠금"
	L["Locks all of the swing bar frames, preventing them from being dragged."] = "모든 공격 바 프레임을 잠가 이동할 수 없게 합니다."
	L[" Welcome Message"] = " 환영 메시지"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "로그인 또는 UI 재시작 시 환영 메시지를 표시합니다. 체크 해제 시 비활성화됩니다."
	L["Ranged Settings"] = "원거리 설정"
	L["Profiles"] = "프로필"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "프로필을 사용하면 여러 레이아웃을 저장하고 빠르게 전환할 수 있습니다."
	L["New profile name"] = "새 프로필 이름"
	L["Create"] = "생성"
	L["Copy from..."] = "다음에서 복사..."
	L["Reset Active Profile"] = "활성 프로필 초기화"
	L["Delete Active Profile"] = "활성 프로필 삭제"
	L["Delete active profile? This cannot be undone."] = "활성 프로필을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
	L["Reset profile to defaults?"] = "프로필을 기본값으로 초기화하시겠습니까?"

	-- Player
	L["Player Swing Bar Settings"] = "플레이어 공격 바 설정"
	L["Enables the player's swing bars."] = "플레이어의 공격 바를 활성화합니다."
	L["Enables the player's off-hand swing bar."] = "플레이어의 보조 손 공격 바를 활성화합니다."
	L["Enables the player bar's border."] = "플레이어 바의 테두리를 활성화합니다."
	L["Enables the classic texture for the player's bars."] = "플레이어 바에 클래식 텍스처를 사용합니다."
	L["Enables the player's left side text."] = "플레이어 바의 왼쪽 텍스트를 활성화합니다."
	L["Enables the player's right side text."] = "플레이어 바의 오른쪽 텍스트를 활성화합니다."
	L["Show Paladin Twist"] = "성기사 트위스트 표시"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "공격 전에 0.4초 마커를 표시하여 인장 트위스트를 돕습니다. 이 마커 이후에 인장을 적용하세요."
	L["Show Paladin GCD"] = "성기사 GCD 표시"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "공격 전에 GCD 마커를 표시하여 인장 트위스트를 돕습니다. 이 마커 이전에 첫 번째 인장을 적용하세요."
	L["Paladin Marker offset"] = "성기사 마커 오프셋"

	-- Target
	L["Target Swing Bar Settings"] = "대상 공격 바 설정"
	L["Enables the target's swing bars."] = "대상의 공격 바를 활성화합니다."
	L["Enables the target's off-hand swing bar."] = "대상의 보조 손 공격 바를 활성화합니다."
	L["Enables the target bar's border."] = "대상 바의 테두리를 활성화합니다."
	L["Enables the classic texture for the target's bars."] = "대상 바에 클래식 텍스처를 사용합니다."
	L["Enables the target's left side text."] = "대상 바의 왼쪽 텍스트를 활성화합니다."
	L["Enables the target's right side text."] = "대상 바의 오른쪽 텍스트를 활성화합니다."

	-- Shot
	L["Failed"] = "실패"
	L["Interrupted"] = "중단됨"
	L["Hunter & Wand Shot Bar Settings"] = "사냥꾼 및 마법봉 사격 바 설정"
	L["General Settings"] = "일반 설정"
	L["YaHT / One bar"] = "YaHT / 단일 바"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] = "자동 사격 바를 왼쪽에서 오른쪽으로 채워지는 단일 바로 변경합니다."
	L["Show Text"] = " 텍스트 표시"
	L["Show Cast Text"] = " 시전 텍스트 표시"
	L["Enables the shot bar text."] = "사격 바 텍스트를 활성화합니다."
	L["Enables the cast bar text."] = "시전 바 텍스트를 활성화합니다."
	L["Auto Shot Cooldown Color"] = "자동 사격 재사용 대기시간 색상"
	L["Auto Shot Cast Color"] = "자동 사격 시전 색상"
	L["Hunter Specific Settings"] = "사냥꾼 전용 설정"
	L["Aimed Shot cast bar"] = "조준 사격 시전 바"
	L["Allows the cast bar to show Aimed Shot casts."] = "시전 바에 조준 사격을 표시합니다."
	L["Multi-Shot cast bar"] = "다중 사격 시전 바"
	L["Allows the cast bar to show Multi-Shot casts."] = "시전 바에 다중 사격을 표시합니다."
	L["Latency bar"] = "지연 시간 바"
	L["Shows a bar that represents latency on cast bar."] = "시전 바에 지연 시간을 나타내는 바를 표시합니다."
	L["Multi-Shot clip bar"] = "다중 사격 클립 바"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] = "다중 사격이 자동 사격을 끊을 시점을 표시합니다."
	L["Auto Shot delay timer"] = "자동 사격 지연 타이머"
	L["Shows a timer that represents when Auto shot is delayed."] = "자동 사격이 지연될 때 타이머를 표시합니다."
	L["Multi-Shot Clip Color"] = "다중 사격 클립 색상"
	L["Spell Bar Unlocked"] = "시전 바 잠금 해제"
	L["Player Spell Bar Settings"] = "플레이어 시전 바 설정"

	-- Common
	L["Main-Hand"] = "주무기"
	L["Off-Hand"] = "보조무기"
	L["Enable"] = " 활성화"
	L["Show Off-Hand"] = " 보조무기 표시"
	L["Show border"] = " 테두리 표시"
	L["Classic bars"] = " 클래식 바"
	L["Fill / Empty"] = " 채우기 / 비우기"
	L["Determines if the bar is full or empty when a swing is ready."] = "공격이 준비되었을 때 바가 채워진 상태인지 비어 있는 상태인지를 결정합니다."
	L["Show Left Text"] = " 왼쪽 텍스트 표시"
	L["Show Right Text"] = " 오른쪽 텍스트 표시"
	L["Bar Width"] = "바 너비"
	L["Bar Height"] = "바 높이"
	L["X Offset"] = "X 오프셋"
	L["Y Offset"] = "Y 오프셋"
	L["Main-hand Bar Color"] = "주무기 바 색상"
	L["Main-hand Bar Text Color"] = "주무기 텍스트 색상"
	L["Off-hand Bar Color"] = "보조무기 바 색상"
	L["Off-hand Bar Text Color"] = "보조무기 텍스트 색상"
	L["In Combat Alpha"] = "전투 중 투명도"
	L["Out of Combat Alpha"] = "비전투 중 투명도"
	L["Backplane Alpha"] = "배경 투명도"
	L["Bar Explanation"] = "바 설명"
	L["Font Size"] = "글꼴 크기"
end

if GetLocale() == "ptBR" then
	-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Obrigado por instalar o WeaponSwingTimer"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "por WatchYourSixx. Use |cFFFFC300/wst|r para mais opções."
	L["Unexpected Unit Type in MissHandler()."] = "Tipo de unidade inesperado em MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."] = "Tipo de unidade inesperado em SpellHandler()."

	-- Config
	L["Global Bar Settings"] = "Configurações globais das barras"
	L["Melee Settings"] = "Configurações de combate corpo a corpo"
	L["Hunter & Wand Settings"] = "Configurações de caçador e varinhas"
	L[" Lock All Bars"] = " Bloquear todas as barras"
	L["Locks all of the swing bar frames, preventing them from being dragged."] = "Bloqueia todas as barras de ataque, impedindo que sejam movidas."
	L[" Welcome Message"] = " Mensagem de boas-vindas"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "Exibe a mensagem de boas-vindas ao entrar ou recarregar. Desmarque para desativar."
	L["Ranged Settings"] = "Configurações de combate à distância"
	L["Profiles"] = "Perfis"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "Os perfis permitem salvar vários layouts e alternar rapidamente entre eles."
	L["New profile name"] = "Nome do novo perfil"
	L["Create"] = "Criar"
	L["Copy from..."] = "Copiar de..."
	L["Reset Active Profile"] = "Redefinir perfil ativo"
	L["Delete Active Profile"] = "Excluir perfil ativo"
	L["Delete active profile? This cannot be undone."] = "Excluir o perfil ativo? Esta ação não pode ser desfeita."
	L["Reset profile to defaults?"] = "Redefinir o perfil para os padrões?"

	-- Player
	L["Player Swing Bar Settings"] = "Configurações das barras de ataque do jogador"
	L["Enables the player's swing bars."] = "Ativa as barras de ataque do jogador."
	L["Enables the player's off-hand swing bar."] = "Ativa a barra de ataque da mão secundária do jogador."
	L["Enables the player bar's border."] = "Ativa a borda da barra do jogador."
	L["Enables the classic texture for the player's bars."] = "Ativa a textura clássica para as barras do jogador."
	L["Enables the player's left side text."] = "Ativa o texto do lado esquerdo da barra do jogador."
	L["Enables the player's right side text."] = "Ativa o texto do lado direito da barra do jogador."
	L["Show Paladin Twist"] = "Mostrar twist do paladino"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "Mostra um marcador de 0,4 s antes do ataque para ajudar no twist de selos. Aplique o selo após este marcador."
	L["Show Paladin GCD"] = "Mostrar GCD do paladino"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "Mostra um marcador de GCD antes do ataque para ajudar no twist de selos. Aplique o primeiro selo antes deste marcador."
	L["Paladin Marker offset"] = "Deslocamento do marcador do paladino"

	-- Target
	L["Target Swing Bar Settings"] = "Configurações das barras de ataque do alvo"
	L["Enables the target's swing bars."] = "Ativa as barras de ataque do alvo."
	L["Enables the target's off-hand swing bar."] = "Ativa a barra de ataque da mão secundária do alvo."
	L["Enables the target bar's border."] = "Ativa a borda da barra do alvo."
	L["Enables the classic texture for the target's bars."] = "Ativa a textura clássica para as barras do alvo."
	L["Enables the target's left side text."] = "Ativa o texto do lado esquerdo da barra do alvo."
	L["Enables the target's right side text."] = "Ativa o texto do lado direito da barra do alvo."

	-- Shot
	L["Failed"] = "Falhou"
	L["Interrupted"] = "Interrompido"
	L["Hunter & Wand Shot Bar Settings"] = "Configurações das barras de disparo de caçador e varinhas"
	L["General Settings"] = "Configurações gerais"
	L["YaHT / One bar"] = "YaHT / Uma barra"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] = "Transforma a barra de Disparo automático em uma única barra que se preenche da esquerda para a direita."
	L["Show Text"] = " Mostrar texto"
	L["Show Cast Text"] = " Mostrar texto de conjuração"
	L["Enables the shot bar text."] = "Ativa o texto na barra de disparo."
	L["Enables the cast bar text."] = "Ativa o texto na barra de conjuração."
	L["Auto Shot Cooldown Color"] = "Cor do tempo de recarga do Disparo automático"
	L["Auto Shot Cast Color"] = "Cor da conjuração do Disparo automático"
	L["Hunter Specific Settings"] = "Configurações específicas do caçador"
	L["Aimed Shot cast bar"] = "Barra de conjuração do Disparo mirado"
	L["Allows the cast bar to show Aimed Shot casts."] = "Permite que a barra de conjuração mostre Disparo mirado."
	L["Multi-Shot cast bar"] = "Barra de conjuração do Disparo múltiplo"
	L["Allows the cast bar to show Multi-Shot casts."] = "Permite que a barra de conjuração mostre Disparo múltiplo."
	L["Latency bar"] = "Barra de latência"
	L["Shows a bar that represents latency on cast bar."] = "Mostra uma barra que representa a latência na barra de conjuração."
	L["Multi-Shot clip bar"] = "Barra de sobreposição do Disparo múltiplo"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] = "Mostra quando o Disparo múltiplo interromperia um Disparo automático."
	L["Auto Shot delay timer"] = "Temporizador de atraso do Disparo automático"
	L["Shows a timer that represents when Auto shot is delayed."] = "Mostra um temporizador quando o Disparo automático é atrasado."
	L["Multi-Shot Clip Color"] = "Cor da sobreposição do Disparo múltiplo"
	L["Spell Bar Unlocked"] = "Barra de feitiços desbloqueada"
	L["Player Spell Bar Settings"] = "Configurações da barra de feitiços do jogador"

	-- Common
	L["Main-Hand"] = "Mão principal"
	L["Off-Hand"] = "Mão secundária"
	L["Enable"] = " Ativar"
	L["Show Off-Hand"] = " Mostrar mão secundária"
	L["Show border"] = " Mostrar borda"
	L["Classic bars"] = " Barras clássicas"
	L["Fill / Empty"] = " Preencher / Esvaziar"
	L["Determines if the bar is full or empty when a swing is ready."] = "Determina se a barra está cheia ou vazia quando o ataque está pronto."
	L["Show Left Text"] = " Mostrar texto esquerdo"
	L["Show Right Text"] = " Mostrar texto direito"
	L["Bar Width"] = "Largura da barra"
	L["Bar Height"] = "Altura da barra"
	L["X Offset"] = "Deslocamento X"
	L["Y Offset"] = "Deslocamento Y"
	L["Main-hand Bar Color"] = "Cor da barra da mão principal"
	L["Main-hand Bar Text Color"] = "Cor do texto da mão principal"
	L["Off-hand Bar Color"] = "Cor da barra da mão secundária"
	L["Off-hand Bar Text Color"] = "Cor do texto da mão secundária"
	L["In Combat Alpha"] = "Transparência em combate"
	L["Out of Combat Alpha"] = "Transparência fora de combate"
	L["Backplane Alpha"] = "Transparência do fundo"
	L["Bar Explanation"] = "Explicação das barras"
	L["Font Size"] = "Tamanho da fonte"
end

if GetLocale() == "ruRU" then
-- Translator ZamestoTV	
-- Core
	L["Thank you for installing WeaponSwingTimer Version"] = "Спасибо за установку WeaponSwingTimer версии"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "от WatchYourSixx! Используйте |cFFFFC300/wst|r для дополнительных настроек."
	L["Unexpected Unit Type in MissHandler()."] = "Неожиданный тип юнита в MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."] = "Неожиданный тип юнита в SpellHandler()."

	-- Config
	L["Global Bar Settings"] = "Общие настройки полос"
	L["Melee Settings"] = "Настройки ближнего боя"
	L["Hunter & Wand Settings"] = "Настройки охотника и жезлов"
	L[" Lock All Bars"] = " Заблокировать все полосы"
	L["Locks all of the swing bar frames, preventing them from being dragged."] = "Блокирует все полосы взмахов, запрещая их перемещение."
	L[" Welcome Message"] = " Приветственное сообщение"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "Показывает приветственное сообщение при входе/перезагрузке UI. Снимите галочку, чтобы отключить."
	L["Ranged Settings"] = "Настройки дальнего боя"
	L["Profiles"] = "Профили"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "Профили позволяют сохранять разные раскладки и быстро переключаться между ними."
	L["New profile name"] = "Название нового профиля"
	L["Create"] = "Создать"
	L["Copy from..."] = "Копировать из..."
	L["Reset Active Profile"] = "Сбросить активный профиль"
	L["Delete Active Profile"] = "Удалить активный профиль"
	L["Delete active profile? This cannot be undone."] = "Удалить активный профиль? Это действие нельзя отменить."
	L["Reset profile to defaults?"] = "Сбросить профиль до настроек по умолчанию?"
	L["Player Spell Bar Settings"] = "Настройки полосы заклинаний игрока"
	L["Font Size"] = "Размер шрифта"
	-- Player
	L["Player Swing Bar Settings"] = "Настройки полосы игрока"
	L["Enables the player's swing bars."] = "Включает полосы взмахов игрока."
	L["Enables the player's off-hand swing bar."] = "Включает полосу взмаха второй рукой."
	L["Enables the player bar's border."] = "Включает рамку полосы игрока."
	L["Enables the classic texture for the player's bars."] = "Включает классическую текстуру для полос игрока."
	L["Enables the player's left side text."] = "Включает текст слева на полосе игрока."
	L["Enables the player's right side text."] = "Включает текст справа на полосе игрока."

	L["Show Paladin Twist"] = "Показывать твист паладина"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "Показывает маркер за 0,4 сек до удара для помощи с твистом печатей. Наносите печать после этого маркера."
	L["Show Paladin GCD"] = "Показывать GCD паладина"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "Показывает маркер ГКД перед ударом для помощи с твистом печатей. Наносите первую печать до этого маркера."
	L["Paladin Marker offset"] = "Смещение маркера паладина"

	-- Target
	L["Target Swing Bar Settings"] = "Настройки полосы цели"
	L["Enables the target's swing bars."] = "Включает полосы взмахов цели."
	L["Enables the target's off-hand swing bar."] = "Включает полосу взмаха второй рукой цели."
	L["Enables the target bar's border."] = "Включает рамку полосы цели."
	L["Enables the classic texture for the target's bars."] = "Включает классическую текстуру для полос цели."
	L["Enables the target's left side text."] = "Включает текст слева на полосе цели."
	L["Enables the target's right side text."] = "Включает текст справа на полосе цели."

	-- Shot
	L["Failed"] = "Промах"
	L["Interrupted"] = "Прервано"
	L["Hunter & Wand Shot Bar Settings"] = "Настройки полосы выстрела охотника и жезлов"
	L["General Settings"] = "Общие настройки"
	L["YaHT / One bar"] = "YaHT / Одна полоса"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"] = "Превращает полосу Автоматической стрельбы в одну полосу, заполняющуюся слева направо"
	L["Show Text"] = "Показывать текст"
	L["Show Cast Text"] = "Показывать текст каста"
	L["Enables the shot bar text."] = "Включает текст на полосе выстрела."
	L["Enables the cast bar text."] = "Включает текст на полосе каста."
	L["Auto Shot Cooldown Color"] = "Цвет кулдауна Автоматической стрельбы"
	L["Auto Shot Cast Color"] = "Цвет каста Автоматической стрельбы"

	L["Hunter Specific Settings"] = "Специфические настройки охотника"
	L["Aimed Shot cast bar"] = "Полоса каста Прицельного выстрела"
	L["Allows the cast bar to show Aimed Shot casts."] = "Позволяет показывать каст Прицельного выстрела на полосе."
	L["Multi-Shot cast bar"] = "Полоса каста Залпа"
	L["Allows the cast bar to show Multi-Shot casts."] = "Позволяет показывать каст Залпа на полосе."
	L["Latency bar"] = "Полоса задержки"
	L["Shows a bar that represents latency on cast bar."] = "Показывает полосу, отображающую задержку на касте."
	L["Multi-Shot clip bar"] = "Полоса клипа Залпа"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."] = "Показывает полосу, когда Залп может клипнуть Автоматическую стрельбу."
	L["Auto Shot delay timer"] = "Таймер задержки Автоматической стрельбы"
	L["Shows a timer that represents when Auto shot is delayed."] = "Показывает таймер, когда Автоматическая стрельба задерживается."
	L["Multi-Shot Clip Color"] = "Цвет клипа Залпа"

	L["Spell Bar Unlocked"] = "Полоса заклинаний разблокирована"

	-- Common
	L["Main-Hand"] = "Основная рука"
	L["Off-Hand"] = "Вторая рука"
	L["Enable"] = "Включить"
	L["Show Off-Hand"] = "Показывать вторую руку"
	L["Show border"] = "Показывать рамку"
	L["Classic bars"] = "Классические полосы"
	L["Fill / Empty"] = "Заполнение / Опустошение"
	L["Determines if the bar is full or empty when a swing is ready."] = "Определяет, полная или пустая полоса, когда удар готов."
	L["Show Left Text"] = "Текст слева"
	L["Show Right Text"] = "Текст справа"

	L["Bar Width"] = "Ширина полосы"
	L["Bar Height"] = "Высота полосы"
	L["X Offset"] = "Смещение по X"
	L["Y Offset"] = "Смещение по Y"

	L["Main-hand Bar Color"] = "Цвет полосы основной руки"
	L["Main-hand Bar Text Color"] = "Цвет текста основной руки"
	L["Off-hand Bar Color"] = "Цвет полосы второй руки"
	L["Off-hand Bar Text Color"] = "Цвет текста второй руки"

	L["In Combat Alpha"] = "Прозрачность в бою"
	L["Out of Combat Alpha"] = "Прозрачность вне боя"
	L["Backplane Alpha"] = "Прозрачность фона"

	L["Bar Explanation"] = "Пояснение к полосам"

	-- Spell
	L["Auto Shot"] = "Автоматическая стрельба"
	L["Feign Death"] = "Притвориться мёртвым"
	L["Trueshot Aura"] = "Аура меткого выстрела"
	L["Multi-Shot"] = "Залп"
	L["Aimed Shot"] = "Прицельный выстрел"
	L["Shoot"] = "Выстрел"
	L["Quick Shots"] = "Быстрые выстрелы"
	L["Rapid Shot"] = "Быстрая стрельба"
	L["Berserking"] = "Берсерк"
	L["Kiss of the Spider"] = "Поцелуй паука"
	L["Curse of Tongues"] = "Проклятие косноязычия"
end

if GetLocale() == "zhCN" then
	--Core
	L["Thank you for installing WeaponSwingTimer Version"] = "感谢您安装WeaponSwingTimer版本！"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "作者：LeftHandedGlove，持续更新：WatchYourSixx，汉化：Cyanokaze。使用|cFFFFC300/wst|r获取更多选项。"
	L["Unexpected Unit Type in MissHandler()."]="Unexpected Unit Type in MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."]="Unexpected Unit Type in SpellHandler()."

	--Config
	L["Global Bar Settings"]="全局设定"
	L["Melee Settings"]="近战武器监控"
	L["Hunter & Wand Settings"]="远程武器监控"
	L["Lock All Bars"]=" 全部锁定"
	L["Locks all of the swing bar frames, preventing them from being dragged."]="锁定所有进度条和窗口，防止它们被移动。"
	L["Click the + on the left for more options"]="点击左侧+显示更多选项。"
	L[" Welcome Message"] = " 欢迎信息"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "登录/重载时显示欢迎信息。取消勾选可关闭。"
	L["Ranged Settings"] = "远程设置"
	L["Profiles"] = "配置文件"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "配置文件可保存多套布局，并可快速切换。"
	L["New profile name"] = "新配置名称"
	L["Create"] = "创建"
	L["Copy from..."] = "复制自..."
	L["Reset Active Profile"] = "重置当前配置"
	L["Delete Active Profile"] = "删除当前配置"
	L["Delete active profile? This cannot be undone."] = "删除当前配置？此操作无法撤销。"
	L["Reset profile to defaults?"] = "将配置重置为默认值？"

	L["Show Paladin Twist"] = " 显示圣骑士扭印"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "在攻击前显示0.4秒标记，帮助扭印；请在该标记后补印。"
	L["Show Paladin GCD"] = " 显示圣骑士GCD"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "在攻击前显示GCD标记，帮助扭印；请在该标记前先上第一道印。"
	L["Paladin Marker offset"] = "圣骑士标记偏移"

	L["Show Cast Text"] = " 施法计时"
	L["Enables the cast bar text."] = "启用施法条文字。"
	L["Spell Bar Unlocked"] = "施法条已解锁"
	L["Player Spell Bar Settings"] = "设置自身施法条"

	L["Font Size"] = "字体大小"
	--Player
	L["Player Swing Bar Settings"]="设置自身武器进度条"
    L["Enables the player's swing bars."]="启用主手武器进度条。"
    L["Enables the player's off-hand swing bar."]="显示副手武器进度条。"
    L["Enables the player bar's border."]="显示进度条边框。"
    L["Enables the classic texture for the player's bars."]="在进度条上启用职业纹理。"
    L["Enables the player's left side text."]="允许在进度条左侧显示武器位置。"
    L["Enables the player's right side text."]="允许在进度右侧显示计时器。"
	--Target
	L["Target Swing Bar Settings"]="设置目标武器进度条"
	L["Enables the target's swing bars."]="启用目标武器进度条。"
    L["Enables the target's off-hand swing bar."]="显示目标副手武器进度条。"
    L["Enables the target bar's border."]="显示目标进度条边框。"
    L["Enables the classic texture for the target's bars."]="在目标进度条上启用职业纹理。"
    L["Enables the target's left side text."]="允许在目标进度条左侧显示武器位置。"
    L["Enables the target's right side text."]="允许在目标进度右侧显示计时器。"
	--Shot
	L["Failed"] = "失败"
	L["Interrupted"] = "打断"
	L["Hunter & Wand Shot Bar Settings"]="设置远程武器进度条"
	L["General Settings"]="基础设置"
	L["YaHT / One bar"]=" 双向/单向"
    L["Changes the Auto Shot bar to a single bar that fills from left to right"]="切换自动射击条为双向/单向。"
    L["Show Text"]=" 计时器"
    L["Enables the shot bar text."]="启用射击进度条文字。"
    L["Auto Shot Cooldown Color"]="自动射击冷却颜色"
    L["Auto Shot Cast Color"]="自动射击颜色"
	L["Hunter Specific Settings"]="猎人特殊设置"
    L["Aimed Shot cast bar"]=" 瞄准射击条"
    L["Allows the cast bar to show Aimed Shot casts."]="允许显示瞄准射击条。"
    L["Multi-Shot cast bar"]=" 多重射击条"
    L["Allows the cast bar to show Multi-Shot casts."]="允许显示多重射击条。"
    L["Latency bar"]=" 延迟条"
    L["Shows a bar that represents latency on cast bar."]="允许显示延迟条。"
    L["Multi-Shot clip bar"]=" 多重射击覆盖区间"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."]="允许显示多重射击覆盖区间。"
	L["Auto Shot delay timer"] = " 自动射击延时器"
	L["Shows a timer that represents when Auto shot is delayed."] = "为自动射击延时显示一个计时器。"
    L["Multi-Shot Clip Color"]="多重射击覆盖区间颜色"
	
    --Common
	L["Main-Hand"]="主手"
	L["Off-Hand"]="副手"
    L["Enable"]=" 启用"
    L["Show Off-Hand"]=" 副手"
    L["Show border"]=" 边框"
    L["Classic bars"]=" 职业纹理"
    L["Fill / Empty"]=" 填充/空白"
    L["Determines if the bar is full or empty when a swing is ready."]="决定武器可用时武器条是填充状态还是空白状态。"
    L["Show Left Text"]=" 武器位置"
    L["Show Right Text"]=" 计时器"
	L["Bar Width"]="宽度"
    L["Bar Height"]="高度"
    L["X Offset"]="X坐标"
    L["Y Offset"]="Y坐标"
	L["Main-hand Bar Color"]="主武器进度条颜色"
    L["Main-hand Bar Text Color"]="主武器文本颜色"
    L["Off-hand Bar Color"]="副武器进度条颜色"
    L["Off-hand Bar Text Color"]="副武器文本颜色"
    L["In Combat Alpha"]="战斗时透明度"
    L["Out of Combat Alpha"]="脱离战斗透明度"
    L["Backplane Alpha"]="底板透明度"
	L["Bar Explanation"]="图片说明："

	--Spell
	L["Auto Shot"]="自动射击"
	L["Feign Death"] = "假死"
	L["Trueshot Aura"] = "强击光环"
	L["Multi-Shot"]="多重射击"
	L["Aimed Shot"]="瞄准射击"
	L["Shoot"]="射击"
	L["Quick Shots"]="快速射击"
	L["Rapid Shot"]="急速射击"
	L["Berserking"]="狂暴"
	L["Kiss of the Spider"]="蜘蛛之吻"
	L["Curse of Tongues"]="语言诅咒"

end
if GetLocale() == "zhTW" then -- 供中国香港、中国澳门和中国台湾省同胞使用

	--Core
	L["Thank you for installing WeaponSwingTimer Version"] = "感謝您安裝WeaponSwingTimer版本"
	L["by WatchYourSixx! Use |cFFFFC300/wst|r for more options."] = "by WatchYourSixx！使用|cFFFFC300/wst|r獲取更多選項。"
	L["Unexpected Unit Type in MissHandler()."]="Unexpected Unit Type in MissHandler()."
	L["Unexpected Unit Type in SpellHandler()."]="Unexpected Unit Type in SpellHandler()."

	--Config
	L["Global Bar Settings"]="全域設定"
	L["Melee Settings"]="近戰武器監控"
	L["Hunter & Wand Settings"]="遠端武器監控"
	L[" Lock All Bars"]=" 全部鎖定"
	L["Locks all of the swing bar frames, preventing them from being dragged."]="鎖定所有進度條和視窗，防止它們被移動。"
	L["Click the + on the left for more options"]="點擊左側+顯示更多選項。"
	L[" Welcome Message"] = " 歡迎訊息"
	L["Displays the welcome message upon login/reload. Uncheck to disable."] = "登入/重載時顯示歡迎訊息。取消勾選可停用。"
	L["Ranged Settings"] = "遠程設定"
	L["Profiles"] = "設定檔"
	L["Profiles let you save multiple layouts and quickly switch between them."] = "設定檔可儲存多套版面配置，並可快速切換。"
	L["New profile name"] = "新設定檔名稱"
	L["Create"] = "建立"
	L["Copy from..."] = "複製自..."
	L["Reset Active Profile"] = "重置目前設定檔"
	L["Delete Active Profile"] = "刪除目前設定檔"
	L["Delete active profile? This cannot be undone."] = "刪除目前設定檔？此操作無法復原。"
	L["Reset profile to defaults?"] = "將設定檔重置為預設值？"

	L["Show Paladin Twist"] = " 顯示聖騎士扭印"
	L["Show 0.4s marker before swing to help with seal twisting. Apply seal after this."] = "在攻擊前顯示0.4秒標記，協助扭印；請在該標記後補印。"
	L["Show Paladin GCD"] = " 顯示聖騎士GCD"
	L["Show GCD marker before swing to help with seal twisting. Apply first seal before this."] = "在攻擊前顯示GCD標記，協助扭印；請在該標記前先上第一道印。"
	L["Paladin Marker offset"] = "聖騎士標記偏移"

	L["Show Cast Text"] = " 施法計時"
	L["Enables the cast bar text."] = "啟用施法條文字。"
	L["Spell Bar Unlocked"] = "施法條已解鎖"
	L["Player Spell Bar Settings"] = "設置自身施法條"

	L["Font Size"] = "字體大小"
	--Player
	L["Player Swing Bar Settings"]="設置自身武器進度條"
	L["Enables the player's swing bars."]="啟用主手武器進度條。"
	L["Enables the player's off-hand swing bar."]="顯示副手武器進度條。"
	L["Enables the player bar's border."]="顯示進度條邊框。"
	L["Enables the classic texture for the player's bars."]="在進度條上啟用職業紋理。"
	L["Enables the player's left side text."]="允許在進度條左側顯示武器位置。"
	L["Enables the player's right side text."]="允許在進度右側顯示計時器。"
	--Target
	L["Target Swing Bar Settings"]="設置目標武器進度條"
	L["Enables the target's swing bars."]="啟用目標武器進度條。"
	L["Enables the target's off-hand swing bar."]="顯示目標副手武器進度條。"
  	L["Enables the target bar's border."]="顯示目標進度條邊框。"
	L["Enables the classic texture for the target's bars."]="在目標進度條上啟用職業紋理。"
	L["Enables the target's left side text."]="允許在目標進度條左側顯示武器位置。"
	L["Enables the target's right side text."]="允許在目標進度右側顯示計時器。"
	--Shot
	L["Failed"] = "失敗"
	L["Interrupted"] = "打斷"
	L["Hunter & Wand Shot Bar Settings"]="設置遠端武器進度條"
	L["General Settings"]="基礎設置"
	L["YaHT / One bar"]=" 雙向/單向"
	L["Changes the Auto Shot bar to a single bar that fills from left to right"]="切換自動射擊條為雙向/單向。"
	L["Show Text"]=" 計時器"
	L["Enables the shot bar text."]="啟用射擊進度條文字。"
	L["Auto Shot Cooldown Color"]="自動射擊冷卻顏色"
	L["Auto Shot Cast Color"]="自動射擊顏色"
	L["Hunter Specific Settings"]="獵人特殊設置"
	L["Aimed Shot cast bar"]=" 瞄準射擊條"
	L["Allows the cast bar to show Aimed Shot casts."]="允許顯示瞄準射擊條。"
	L["Multi-Shot cast bar"]=" 多重射擊條"
	L["Allows the cast bar to show Multi-Shot casts."]="允許顯示多重射擊條。"
	L["Latency bar"]=" 延遲條"
	L["Shows a bar that represents latency on cast bar."]="允許顯示延遲條。"
	L["Multi-Shot clip bar"]=" 多重射擊覆蓋區間"
	L["Shows a bar that represents when a Multi-Shot would clip an Auto Shot."]="允許顯示多重射擊覆蓋區間。"
	L["Auto Shot delay timer"] = " 自動射擊延時器"
	L["Shows a timer that represents when Auto shot is delayed."] = "為自動射擊延時顯示一個計時器。"
	L["Multi-Shot Clip Color"]="多重射擊覆蓋區間顏色"
	
    	--Common
	L["Main-Hand"]="主手"
	L["Off-Hand"]="副手"
	L["Enable"]=" 啟用"
	L["Show Off-Hand"]=" 副手"
	L["Show border"]=" 邊框"
	L["Classic bars"]=" 職業紋理"
	L["Fill / Empty"]=" 填充/空白"
	L["Determines if the bar is full or empty when a swing is ready."]="決定武器可用時武器條是填充狀態還是空白狀態。"
	L["Show Left Text"]=" 武器位置"
	L["Show Right Text"]=" 計時器"
	L["Bar Width"]="寬度"
	L["Bar Height"]="高度"
	L["X Offset"]="X座標"
	L["Y Offset"]="Y座標"
	L["Main-hand Bar Color"]="主武器進度條顏色"
	L["Main-hand Bar Text Color"]="主武器文本顏色"
	L["Off-hand Bar Color"]="副武器進度條顏色"
	L["Off-hand Bar Text Color"]="副武器文本顏色"
	L["In Combat Alpha"]="戰鬥時透明度"
	L["Out of Combat Alpha"]="脫離戰鬥透明度"
	L["Backplane Alpha"]="底板透明度"
	L["Bar Explanation"]="圖片說明："

	--Buffs need true name.
	L["Auto Shot"]="自動射擊"
	L["Feign Death"] = "假死"
	L["Trueshot Aura"] = "強擊光環"
	L["Multi-Shot"]="多重射擊"
	L["Aimed Shot"]="瞄準射擊"
	L["Shoot"]="射擊"
	L["Quick Shots"]="快速射擊"
	L["Rapid Shot"]="急速射擊"
	L["Berserking"]="狂暴"
	L["Kiss of the Spider"]="蜘蛛之吻"
	L["Curse of Tongues"]="語言詛咒"
	
end


